CREATE TABLE users (
 id BIGINT PRIMARY KEY AUTO_INCREMENT,
 email VARCHAR(255) NOT NULL UNIQUE,
 name VARCHAR(255), provider VARCHAR(50) NOT NULL,
 provider_id VARCHAR(255),
 role VARCHAR(255) DEFAULT 'ROLE_USER',
 created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
 updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE facebook_accounts (
 id BIGINT PRIMARY KEY AUTO_INCREMENT,
 user_id BIGINT NOT NULL,
 facebook_user_id VARCHAR(50) NOT NULL,
 access_token TEXT NOT NULL,
 token_expires_at TIMESTAMP NULL,
 created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
 updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
 CONSTRAINT fk_facebook_user FOREIGN KEY (user_id) REFERENCES users(id)
);
CREATE TABLE facebook_pages (
 id BIGINT PRIMARY KEY AUTO_INCREMENT,
 fb_account_id BIGINT NOT NULL,
 page_id VARCHAR(50) NOT NULL,
 page_name VARCHAR(255),
 page_access_token TEXT NOT NULL,
 created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
 updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
 CONSTRAINT fk_fb_account FOREIGN KEY (fb_account_id) REFERENCES facebook_accounts(id),
 UNIQUE (page_id)
 );

CREATE TABLE posts (
 id BIGINT PRIMARY KEY AUTO_INCREMENT,
 user_id BIGINT NOT NULL,
 fb_page_id BIGINT NOT NULL,
 message TEXT NOT NULL,
 status VARCHAR(20) NOT NULL,
 fb_post_id VARCHAR(100),
 error_message TEXT,
 created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
 CONSTRAINT fk_post_user FOREIGN KEY (user_id) REFERENCES users(id),
 CONSTRAINT fk_post_page FOREIGN KEY (fb_page_id) REFERENCES facebook_pages(id)

);